# Generated by Django 5.0.1 on 2024-02-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=200)),
                ('Capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('Cost', models.IntegerField(blank=True, default=0, null=True)),
                ('news_image', models.FileField(default=None, max_length=250, null=True, upload_to='news/')),
            ],
        ),
    ]
