# Generated by Django 5.0.1 on 2024-02-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venues', '0002_remove_venues_news_image_venues_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venues',
            name='Venue_image',
        ),
        migrations.AddField(
            model_name='venues',
            name='Venue_images',
            field=models.ManyToManyField(blank=True, related_name='venues', to='Venues.venues'),
        ),
    ]
