# Generated by Django 5.0.1 on 2024-02-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Venues', '0003_remove_venues_venue_image_venues_venue_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venues',
            old_name='Venue_images',
            new_name='Venue_image',
        ),
    ]
