# Generated by Django 5.0.1 on 2024-02-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venues', '0005_remove_venues_venue_image_venues_venue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venues',
            name='Venue_image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='venues/'),
        ),
    ]
