# Generated by Django 5.0.1 on 2024-02-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venues', '0006_alter_venues_venue_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venues/')),
            ],
        ),
        migrations.RemoveField(
            model_name='venues',
            name='Venue_image',
        ),
        migrations.AddField(
            model_name='venues',
            name='Venue_image',
            field=models.ManyToManyField(to='Venues.imagefile'),
        ),
    ]
