# Generated by Django 5.0.1 on 2024-04-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decbooking', '0002_rename_enddate_decbooking_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decbooking',
            name='user',
        ),
        migrations.AddField(
            model_name='decbooking',
            name='User',
            field=models.CharField(default='', max_length=100),
        ),
    ]
