# Generated by Django 5.0.1 on 2024-05-17 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decbooking', '0003_remove_decbooking_user_decbooking_user'),
        ('decoration', '0005_rename_venue_image_decoration_decoration_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='decorationBookingWithKhalti',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('enddate', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('decoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decoration.decoration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
