# Generated by Django 5.0.1 on 2024-05-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decbooking', '0004_decorationbookingwithkhalti'),
    ]

    operations = [
        migrations.AddField(
            model_name='decbooking',
            name='payment_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
