# Generated by Django 5.0.1 on 2024-02-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Phone_Number', models.IntegerField(default=None, max_length=250, null=True)),
                ('Email', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Photography_type', models.CharField(max_length=200)),
                ('Event_type', models.CharField(max_length=200)),
                ('Cost', models.IntegerField(blank=True, default=0, null=True)),
                ('Image', models.FileField(default=None, max_length=250, null=True, upload_to='photography/')),
            ],
        ),
    ]
