# Generated by Django 5.0.1 on 2024-02-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='Type',
        ),
        migrations.AlterField(
            model_name='photographer',
            name='Phone_Number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
