# Generated by Django 5.0.1 on 2024-04-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0003_imagefile_remove_photographer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='Description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
