# Generated by Django 5.0.1 on 2024-04-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0004_photographer_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographer',
            name='Photography_type',
        ),
    ]
