# Generated by Django 5.0.1 on 2024-04-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographerbooking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photographerbooking',
            old_name='endDate',
            new_name='end_date',
        ),
    ]
