# Generated by Django 5.0.1 on 2024-04-21 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographerbooking', '0002_rename_enddate_photographerbooking_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photographerbooking',
            old_name='name',
            new_name='username',
        ),
    ]
