# Generated by Django 5.0.1 on 2024-04-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographerbooking', '0003_rename_name_photographerbooking_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographerbooking',
            name='user',
        ),
        migrations.AddField(
            model_name='photographerbooking',
            name='User',
            field=models.CharField(default='', max_length=100),
        ),
    ]
