# Generated by Django 5.0.1 on 2024-02-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decoration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decoration',
            name='Booking_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
