# Generated by Django 5.0.1 on 2024-04-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decoration', '0003_imagefile_remove_decoration_booking_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decoration',
            name='Decoration_image',
        ),
        migrations.AddField(
            model_name='decoration',
            name='Venue_image',
            field=models.ManyToManyField(to='decoration.imagefile'),
        ),
    ]
