# Generated by Django 5.0.1 on 2024-02-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_id', models.IntegerField(blank=True, default=0, null=True)),
                ('Event_Type', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Capacity', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Decoration', models.CharField(max_length=100)),
                ('Photography', models.CharField(max_length=100)),
                ('Date', models.DateTimeField()),
                ('Cost', models.IntegerField(blank=True, default=0, null=True)),
                ('Image', models.FileField(default=None, max_length=250, null=True, upload_to='decoration/')),
            ],
        ),
    ]
