# Generated by Django 5.0.1 on 2024-04-16 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(default='', max_length=100)),
                ('Type', models.CharField(default='', max_length=100)),
                ('Event_Type', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Capacity', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Decoration', models.CharField(max_length=100)),
                ('Photography', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('EndDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('Cost', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
