# Generated by Django 5.0.1 on 2024-04-02 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Booking_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Image',
        ),
    ]
