# Generated by Django 5.0.1 on 2024-04-03 07:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_booking_id_remove_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='EndDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
