# Generated by Django 5.0.1 on 2024-05-13 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venues', '0007_imagefile_remove_venues_venue_image_and_more'),
        ('booking', '0003_alter_booking_venue_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueBookingWithKhalti',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('enddate', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=100)),
                ('pid', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Venues.venues')),
            ],
        ),
    ]
