# Generated by Django 5.0.1 on 2024-04-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_date_booking_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
